### ISSUE TITLE
Почему возвращать должен user.Storage, но возвращает ссылку на db?

### ISSUE THREAD

**Issue by adminoid** [theartofdevel/go-advanced-lessons#1]
Подскажите, пожалуйста, вот:
```go
func NewStorage(database *mongo.Database, collection string, logger *logging.Logger) user.Storage {
	return &db{
		collection: database.Collection(collection),
		logger:     logger,
	}
}
```
Почему возвращать должен user.Storage, но возвращает ссылку на db? И даже ошибок нет, что это за фича и как она работает?

**Comment by hawkkiller** [comment]
Потому что сторедж это интерфейс, а db структура, которая его реализует

**Comment by adminoid** [comment]
Спасибо, разобрался!
